before_script:
  - echo "Running Test Setup"

unittests:
  script:
    - export QT_QPA_PLATFORM=minimal
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=ON ..
    - make -j4
    - make coverage
  except:
    - /^\d+(\.\d+)+/
  tags:
    - fedora
