before_script:
  - echo "Running Test Setup"

unittests:
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=ON ..
    - make -j4
    - make coverage
  except:
    - /^\d+(\.\d+)+/
  artifacts:
    when: always
    paths:
      - build/coverage/html/
