before_script:
  - echo "Running Test Setup"
  - export CTEST_OUTPUT_ON_FAILURE=1

unittests:
  image: registry.gitlab.com/rpdev/opentodolist:fedora
  script:
    - export QT_QPA_PLATFORM=minimal
    - mkdir build
    - cd build
    - qmake-qt5 ..
    - make -j4
    - make check
  only:
    - branches
