before_script:
  - echo "Running Test Setup"
  - export CTEST_OUTPUT_ON_FAILURE=1

unittests:
  tags:
    - fedora
  script:
    - export QT_QPA_PLATFORM=minimal
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - make test
  only:
    - branches
