variables:
    FEDORA_IMAGE: registry.gitlab.com/rpdev/opentodolist:fedora
    FEDORA_SYSTEM_IMAGE: registry.gitlab.com/rpdev/opentodolist:fedora_system
    WIN32_IMAGE: registry.gitlab.com/rpdev/opentodolist:win32
    WIN64_IMAGE: registry.gitlab.com/rpdev/opentodolist:win64
    MXE_WIN32_IMAGE: registry.gitlab.com/rpdev/opentodolist:mxe_win32
    MXE_WIN64_IMAGE: registry.gitlab.com/rpdev/opentodolist:mxe_win64
    UBUNTU_IMAGE: registry.gitlab.com/rpdev/opentodolist:ubuntu
    NEXTCLOUD_IMAGE: nextcloud

stages:
  - images
  - build
  - test
  - deploy

before_script:
  - export CTEST_OUTPUT_ON_FAILURE=1



################################################################################
# Images Stage
################################################################################

# Build the Linux (Fedora) Image
build_image_fedora:
  stage: images
  image: docker:git
  services:
  - docker:dind
  script:
    - cd ci/docker/fedora
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --pull -t $FEDORA_IMAGE .
    - docker push $FEDORA_IMAGE
  when: manual


# Build the Linux (Fedora) Image including system
# provided optional dependencies:
build_image_fedora_system:
  stage: images
  image: docker:git
  services:
  - docker:dind
  script:
    - cd ci/docker/fedora_system
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --pull -t $FEDORA_SYSTEM_IMAGE .
    - docker push $FEDORA_SYSTEM_IMAGE
  when: manual


# Build the Linux (Ubuntu) Image
build_image_ubuntu:
  stage: images
  image: docker:git
  services:
  - docker:dind
  script:
    - cd ci/docker/ubuntu
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --pull -t $UBUNTU_IMAGE .
    - docker push $UBUNTU_IMAGE
  when: manual


# Build the Win32 Image
build_image_win32:
  stage: images
  image: docker:git
  services:
  - docker:dind
  script:
    - cd ci/docker/win32
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --pull -t $WIN32_IMAGE .
    - docker push $WIN32_IMAGE
  when: manual


# Build the Win64 Image
build_image_win64:
  stage: images
  image: docker:git
  services:
  - docker:dind
  script:
    - cd ci/docker/win64
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --pull -t $WIN64_IMAGE .
    - docker push $WIN64_IMAGE
  when: manual


################################################################################
# Build Stage
################################################################################

# Linux build & unit tests with built-in libraries
linux_builtin:
  stage: build
  image: $FEDORA_IMAGE
  services:
    - name: $NEXTCLOUD_IMAGE
      alias: nextcloud
  script:
    - curl -d install="true" -d adminlogin=admin -d adminpass=admin http://nextcloud/index.php
    - export QT_QPA_PLATFORM=minimal
    - mkdir build
    - cd build
    - qmake-qt5 CONFIG+=with_nextcloud_tests NEXTCLOUD_URL=http://nextcloud NEXTCLOUD_USER=admin NEXTCLOUD_PASSWORD=admin ..
    - make -j4
    - make check
  only:
    - branches
  artifacts:
    paths:
      - build
    expire_in: 1 week


# Linux build & unit tests with system provides libraries
linux_system:
  stage: build
  image: $FEDORA_SYSTEM_IMAGE
  services:
    - name: $NEXTCLOUD_IMAGE
      alias: nextcloud
  script:
    - curl -d install="true" -d adminlogin=admin -d adminpass=admin http://nextcloud/index.php
    - export QT_QPA_PLATFORM=minimal
    - mkdir build
    - cd build
    - qmake-qt5 CONFIG+=with_nextcloud_tests NEXTCLOUD_URL=http://nextcloud NEXTCLOUD_USER=admin NEXTCLOUD_PASSWORD=admin ..
    - make -j4
    - make check
  only:
    - branches
  artifacts:
    paths:
      - build
    expire_in: 1 week


# Ubuntu build including AppImage
ubuntu_appimage:
  stage: build
  image: $UBUNTU_IMAGE
  services:
    - name: $NEXTCLOUD_IMAGE
      alias: nextcloud
  script:
    - curl -d install="true" -d adminlogin=admin -d adminpass=admin http://nextcloud/index.php
    - desktop-file-validate templates/appimage/default.desktop
    - export QT_QPA_PLATFORM=minimal
    - mkdir build
    - cd build
    - source /opt/qt59/bin/qt59-env.sh || true # Ignore errors during sourcing
    - qmake CONFIG+=RELEASE CONFIG+=with_nextcloud_tests NEXTCLOUD_URL=http://nextcloud NEXTCLOUD_USER=admin NEXTCLOUD_PASSWORD=admin ..
    - make -j4
    - make check
    - make OpenTodoList-x86_64.AppImage
  only:
    - branches
  artifacts:
    paths:
      - build
    expire_in: 1 week


# Windows 32bit build
win32_build:
  stage: build
  image: $MXE_WIN32_IMAGE
  script:
    - mkdir build-win32
    - cd build-win32
    - export PATH=/opt/mxe-i686-shared/usr/bin:$PATH
    - export PATH=/opt/mxe-i686-shared/usr/i686-w64-mingw32.shared/qt5/bin:$PATH
    - qmake CONFIG+=release ..
    - make -j4
    - cd ..
    - mkdir -p deploy-win32/OpenTodoList
    - cp build-win32/app/release/OpenTodoList.exe deploy-win32/OpenTodoList/
    - apt-get update
    - apt-get install -y wget python3
    - wget https://gitlab.com/rpdev/xwindeployqt/raw/master/xwindeployqt
    - chmod +x xwindeployqt
    - xwindeployqt --toolchain-root /opt/mxe-i686-shared/ --toolchain-arch i686-w64-mingw32.shared --qml-dir ./app --plugins bearer --plugins imageformats --plugins sqldrivers deploy-win32/OpenTodoList/
  only:
    - branches
  artifacts:
    paths:
      - build-win32
      - deploy-win32
    expire_in: 1 week


# Windows 64bit build
win64_build:
  stage: build
  image: $MXE_WIN64_IMAGE
  script:
    - mkdir build-win64
    - cd build-win64
    - export PATH=/opt/mxe-x64-shared/usr/bin:$PATH
    - export PATH=/opt/mxe-x64-shared/usr/x86_64-w64-mingw32.shared/qt5/bin:$PATH
    - qmake CONFIG+=release ..
    - make -j4
    - cd ..
    - mkdir -p deploy-win64/OpenTodoList
    - cp build-win64/app/release/OpenTodoList.exe deploy-win64/OpenTodoList/
    - apt-get update
    - apt-get install -y wget python3
    - wget https://gitlab.com/rpdev/xwindeployqt/raw/master/xwindeployqt
    - chmod +x xwindeployqt
    - xwindeployqt --toolchain-root /opt/mxe-x64-shared/ --toolchain-arch x86_64-w64-mingw32.shared --qml-dir ./app --plugins bearer --plugins imageformats --plugins sqldrivers deploy-win32/OpenTodoList/
  only:
    - branches
  artifacts:
    paths:
      - build-win64
      - deploy-win64
    expire_in: 1 week
